### ISSUE TITLE
Stylelints latest update is failing due to node version.

### ISSUE THREAD

**Issue by 96StanleyLee** [exelban/stylelint#9]
Similar to the issue resolved here: https://github.com/actions-hub/stylelint/issues/4

Stylelint had a new update today which breaks the action due to needing a higher node version.

`Expected version “^12.20.0 || ^14.13.1 || >=16.0.0”. Got “12.16.1"`

@exelban Is there a way to remedy this or would you have to update the base image that you are currently pulling from?

**Comment by exelban** [comment]
Ok, looks like it's fixed. Please give me to know if you still have a problem.
